### ISSUE TITLE
Data race is detected at flag.Usage modification

### ISSUE THREAD

**Issue by Jwata** [maruel/subcommands#7]
When running tests in parallel, sometimes race detector (go test -race) fails at the following line. https://github.com/maruel/subcommands/blob/4b22346b79dd1f53c945985bb1243cc141f70aa7/subcommands.go#L334

Example:
https://logs.chromium.org/logs/infra/buildbucket/cr-buildbucket.appspot.com/8856422888007344336/+/u/go_test_-race/stdout#L6231_51

**Comment by maruel** [comment]
Published v1.0.1
